include:
  - path: 'network/docker-compose.network.yml'
  - path: 'server/docker-compose.server.yml'
  - path: 'security/docker-compose.security.yml'
  - path: 'media/docker-compose.media.yml'
  - path: 'data/docker-compose.data.yml'
  - path: 'databases/docker-compose.databases.yml'
  - path: 'remote/docker-compose.remote.yml'
