networks:
  nextcloud-internal: {}

services:
  nextcloud:
    container_name: nextcloud
    image: 'nextcloud:${NEXTCLOUD_IMAGE_VERSION:-latest}'
    depends_on:
      - 'nextcloud-db'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
    networks:
      - 'home'
      - 'nextcloud-internal'
    ports:
      - ${NEXTCLOUD_PORT}:80
    restart: 'unless-stopped'
    volumes:
      - '${HDD_DATA_DIRECTORY}/nextcloud:/var/www/html'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_DATABASE=NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=redis

  nextcloud-db:
    container_name: nextcloud-db
    image: 'mariadb'
    command: '--transaction-isolation=READ-COMMITTED --binlog-format=ROW'
    environment:
      MYSQL_DATABASE: '${NEXTCLOUD_MYSQL_DATABASE:-nextcloud}'
      MYSQL_PASSWORD: '${NEXTCLOUD_MYSQL_PASSWORD:-nextcloud}'
      MYSQL_ROOT_PASSWORD: '${NEXTCLOUD_MYSQL_ROOT_PASSWORD:-pass}'
      MYSQL_USER: '${NEXTCLOUD_MYSQL_USER:-nextcloud}'
    healthcheck:
      test: ['CMD', 'mysqlcheck', '--all-databases', '-ppass']
    networks:
      - 'nextcloud-internal'
    restart: 'always'
    volumes:
      - './db:/var/lib/mysql'
  
  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    networks: 
      - cloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - password=${NEXTCLOUD_COLLABORA_PASSWORD}
      - username=${NEXTCLOUD_COLLABORA_USERNAME}
      - domain=${DOMAIN_NAME}
      - extra_params=--o:ssl.enable=true
    ports:
      - 9980:9980

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data  
    networks: 
      - home 