services:
  xbvr:
    image: ghcr.io/xbapps/xbvr:latest
    container_name: xbvr
    restart: unless-stopped
    ports:
      - 9999:9999
    networks:
      - home
    volumes:
      - ${HDD_DATA_DIRECTORY}/xbvr:/videos
      - ./config:/root/.config/
