services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.1.225
    ports:
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp 
    volumes:
      - ./adguardhome/conf:/opt/adguardhome/conf
      - ./adguardhome/work:/opt/adguardhome/work
      # - $DOCKERDIR/shared/certs/example.com:/certs #if using own certs

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp0s31f6
    ipam:
      config:
        - subnet: "192.168.154.0/24"
          ip_range: "192.168.154.225/32"
          gateway: "192.168.154.1"