services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 5055:5055 # Overseerr
      - 4545:4545 # Requestrr
      - 6969:6969 # Whisparr
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - VPN_DISABLE_IPV6=true
      - WIREGUARD_PRIVATE_KEY= RcUmM2MqvpmsXLWO4a523b/nXGP7yZlW+4bNakZ5aNw=
      - DNS=1.1.1.1
      - SERVER_COUNTRIES=Netherlands
      # Timezone for accurate log times
      - TZ=${TZ}
    network_mode: home
    labels:
        - com.centurylinklabs.watchtower.enable=false #Disables Watchtower
    security_opt:
        - no-new-privileges:true #For security

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8085
      - UMASK=022
    volumes:
      - ./qbittorrent/config:/config
      - ${HDD_DATA_DIRECTORY}/servarr/qbittorrent/torrents:/Media/Torrents
    depends_on:
      gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Series:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./radarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Movies:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./lidarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Music:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  whisparr:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./whisparr/config:/config
      - ${HDD_DATA_DIRECTORY}/xbvr/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ./overseerr/config:/app/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    network_mode: "service:gluetun"
    volumes:
      - ./requestrr/config:/root/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    network_mode: service:gluetun #Replace this bridge if you don’t use GlueTUN
    restart: unless-stopped
    volumes:
      - ./tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    depends_on: #use this if you use GlueTUN for VPN
      gluetun:
        condition: service_healthy