services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 5055:5055 # Jellyseerr
      - 4545:4545 # Requestrr
      - 6969:6969 # Whisparr
      - 9117:9117 # Jackett
      - 8080:8080 # Sabnzbd
      - 8096:8096 # Jellyfin
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - VPN_DISABLE_IPV6=true
      - WIREGUARD_PRIVATE_KEY= RcUmM2MqvpmsXLWO4a523b/nXGP7yZlW+4bNakZ5aNw=
      - DNS=1.1.1.1
      - SERVER_COUNTRIES=Netherlands
      # Timezone for accurate log times
      - TZ=${TZ}
    network_mode: home
    labels:
        - com.centurylinklabs.watchtower.enable=false #Disables Watchtower
    security_opt:
        - no-new-privileges:true #For security

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8085
      - UMASK=022
    volumes:
      - ./qbittorrent/config:/config
      - ${HDD_DATA_DIRECTORY}/servarr/qbittorrent/torrents:/Media/Torrents
    depends_on:
      gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./sonarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Series:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./radarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Movies:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./lidarr/config:/config
      - ${HDD_DATA_DIRECTORY}/Media/Music:/Media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  whisparr:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./whisparr/config:/config
      - ${HDD_DATA_DIRECTORY}/xbvr/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ./jellyseer:/app/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  requestrr:
    image: darkalfx/requestrr
    container_name: requestrr
    network_mode: "service:gluetun"
    volumes:
      - ./requestrr/config:/root/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    network_mode: service:gluetun #Replace this bridge if you don’t use GlueTUN
    restart: unless-stopped
    volumes:
      - ./tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    depends_on: #use this if you use GlueTUN for VPN
      gluetun:
        condition: service_healthy

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: service:gluetun
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./jackett/config:/config
    - ${HDD_DATA_DIRECTORY}/servarr/jackett/downloads:/downloads
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./sabnzbd/config:/config
      - ${HDD_DATA_DIRECTORY}/servarr/sabnzbd:/Media
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      gluetun:
        condition: service_healthy

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: service:gluetun
    volumes:
      - ./jellyfin:/config
      - /home/daan/data/Media:/data/media
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    depends_on:
      gluetun:
        condition: service_healthy

  spotweb:
    image: erikdevries/spotweb
    container_name: spotweb
    environment:
      - TZ=${TZ} #CHANGE_TO_YOUR_TZ
      - DB_PORT=3306
      - DB_HOST=spotweb_db
      - DB_NAME=spotweb
      - DB_USER=spotweb #username from line 32
      - DB_PASS=spotweb #password from line 33
      - CRON_INTERVAL=*/5 * * * *
    network_mode: service:gluetun
    depends_on:
      spotweb_db:
        condition: service_healthy
      gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: always

  spotweb_db:
    image: linuxserver/mariadb:latest
    container_name: spotweb_db
    environment:
      - MYSQL_ROOT_PASSWORD=StRoNgPa55WoRd
      - PUID=1000 #CHANGE_TO_YOUR_UID
      - PGID=1000 #CHANGE_TO_YOUR_GID
      - TZ=${TZ} #CHANGE_TO_YOUR_TZ
      - MYSQL_DATABASE=spotweb
      - MYSQL_USER=spotweb #A username
      - MYSQL_PASSWORD=spotweb # Another database password
    volumes:
      - ./spotweb/spotweb-mariadb:/config
    network_mode: service:gluetun
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "spotweb_db"]
      timeout: 20s
      retries: 10
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      gluetun:
        condition: service_healthy